sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: skyline_takeaway
    username: heima
    password: 123456
  file:
    local-oss-path: D:/images/
    local-oss-url: http://localhost:8080
  redis:
    host: localhost
    port: 6379
    password: 114514
    database: 0


